# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'houseApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for houseApp
  # Pods for firebase
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'  
  # Pods for facebook login
  pod 'FacebookCore'
  pod 'FacebookLogin'
  #Pod for handling the request to database
  pod 'PromiseKit', '~> 6.0'
  #Pod for parsing the request of database
  pod 'ObjectMapper'
end
